name: Open Rubric CamtasiaWin PR Dispatcher Action Responder

on:
  repository_dispatch:
    types: [ping]

jobs:
  action_responder:
    if: ${{ startsWith(github.event.client_payload.branch, 'rubricTranslation/') }}
    runs-on: ubuntu-latest
    env:
      Repository: ${{ github.event.client_payload.repository }}
      Branch: ${{ github.event.client_payload.branch }}
    steps:
      - name: PONG
        run: echo "Repository $Repository Branch $Branch"
      - name: Checkout Rubric Branch
        uses: actions/checkout@v4
        with:
          ref: Branch
          run: echo "Checkout branch ${{github.head_ref}}
            
          
