name: Open Rubric CamtasiaWin PR Dispatcher Action Responder

on:
  repository_dispatch:
    types: [ping]

jobs:
  action_responder:
    env:
      Repository: ${{ github.event.client_payload.repository }}
      Branch: ${{ github.event.client_payload.branch }}
    if: ${{ startsWith(env.Branch, 'rubricTranslation/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Initiator Reop and Branch
        run: echo "Repository $Repository Branch $Branch"
      - name: Checkout Rubric Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.Branch }}
      - name: Echo Checked-out Branch
        run: echo "Checkout branch ${{ github.head_ref }}"
            
          
