name: Action Responder

on:
  repository_dispatch:
    types: [ping]

jobs:
  action_responder:
    runs-on: ubuntu-latest
    steps:
      - name: PONG
        env:
          Repository: ${{ github.event.client_payload.repository }}
          Branch: ${{ github.event.client_payload.branch }}
        run: echo "Repository $Repository Branch $Branch"
